import {PaletteMode} from '@mui/material';

export const lightPalette = {
    mode: 'light' as PaletteMode,
    custom: {},
    common: {
        white: '#ffffff',
        black: '#000000',
        grey: '#90caf9',
    },
    background: {
        logo: '#203062',
        main: `#FFFFFF`,
        card: '#ffffff',
        cardSecondary: '#ffffff',
        tooltip: '#3466CC',
        navigation: '#6487E920',
        button: '#FFFFFF',
        buttonActive: '#3466CC',
        popper: '#FFFFFF',
        popperHighlight: '#5188F6',
        menu: '#FFFFFF',
        menuHighlight: '#5188F6',
        glassModal: '#FFFFFF',
        solidModal: '#FFFFFF',
        confirmationModal: '#FFFFFF',
        confirmationModalField: '#FFFFFF',
        tableFilter: '#FFFFFF',
        default: '#070E1B',
        dropdown: '#FFFFFF',
        disabled: '#88AFFF',
        avatar: '#19224B',
    },
    cta: {
        primary: '#3466CC',
        disabled: '#88AFFF',
    },
    text: {
        title: '#101010',
        primary: '#101010',
        secondary: '#3466CC',
        tooltip: '#FFFFFF',
        icon: '#3F3F3F',
        card: '#5F5F5F',
        cardSecondary: '#101010',
        tabActive: '#FFFFFF',
        tabInactive: '#3466CC',
        disabled: '#787F8F',
        disabledButton: '#FFFFFF',
    },
    border: {
        thumbnail: '#EBEBEB',
        card: '#EBEBEB',
        buttonActive: '#3466CC', // use border-image-source for this
        buttonInactive: '#3466CC',
        divider: '#CCCCCC',
        checkbox: '#6AA6FF',
        buttonGroup: '#3E61C3',
    },
    success: {
        main: '#009C22',
    },
    warning: {
        main: '#FFCE21',
    },
    error: {
        main: '#FF4E4E',
    },
    info: {
        main: '#29D9FF',
    },
    graph: {
        tooltip: '#3466CC',
        tooltipText: '#ffffff',
        tooltipLabel: '#ffffff',
        label: '#BABABA',
        button: '#D9D9D9',
        line: '#0ECEF6',
    },
    table: {
        hover: '#202E64',
        active: '#213BA3',
        label: '#9B9B9B',
        text: '#FFFFFF',
        radioBorder: '#68A2F9',
        radioBg: '#202E64',
    },
    tooltip: {
        color: '#1D2D4E',
    },
    scrollbar: {
        thumb: '#3466cc',
        track: '#2b2b2b',
        trackBackground: '#070E1B09',
        thumbFocus: '#3466cc',
        thumbActive: '#3466cc',
        thumbHover: '#3466cc',
        thumbCorner: '#2b2b2b',
    },
};
